### PR TITLE
[Back-End] API Schema Creation

### LINKED ISSUE #9: [Back-End] API Schema Creation

### PR DESCRIPTION
**Pull request by CoachBenedetto**
Fixes #9

### CODE REVIEW

**Comment by CoachBenedetto** [comment]
The amplify folder cannot be removed from frontend folder

**Comment by apolat2000** [comment]
As I was reading through, I stumbled upon this line in `admin-app/frontend/amplify/backend/api/adminapp/cli-inputs.json`:

> `"gqlSchemaPath": "/Users/aktionsodis/Documents/Entwicklung/SodisGit/software-main/admin-app/frontend/amplify/backend/api/adminapp/schema.graphql",`

Apparently, this is an absolute path in your computer.

This will cause problems on the long run and apparently our back-end should most probably run inside a docker container for avoiding such environment-bound problems.

But since this is not relevant to the problem this pull request is solving, I am approving it.

**Review by apolat2000 — APPROVED** [review]
LGTM except:

`admin-app/frontend/amplify/src/graphql/schema.json` is a really big generated file. We will consider untracking and ignoring it, but it doesn't harm ATM, so approved :+1:.

**Comment by CoachBenedetto** [comment]
As it is now okay, I will close this issue?

**Pull request closed without merging**
