### PR TITLE
193/analytics app add amplify user login

### PR DESCRIPTION
**Pull request by benjaminsimeon**
The issue: #193

### CODE REVIEW

**Comment by apolat2000** [comment]
@benjaminsimeon Why do we have register functionality? We shouldn't have that AFAIK, since account creation was planned to be done only by people from the organization with admin access to Amplify Studio.

**Comment by apolat2000** [comment]
Maybe already obvious but I'll write it just for the record: we will need a forgot my password functionality.

**Comment by apolat2000** [comment]
The functionality is not complete yet. We definitely need the first login flow, i. e. when an admin creates an account for an organization member and sets the initial password, nothing happens when the member enters these credentials in the Analytics-App. Refer to the Admin-App for the flow, since it is already implemented there.

**Comment by benjaminsimeon** [comment]
We can add the forgot my password functionality in another release

**Review by apolat2000 — APPROVED** [review]
Good enough for pitching purposes.

**Pull request merged**
