### PR TITLE
created dataStorePathes for dart

### PR DESCRIPTION
**Pull request by CoachBenedetto**
Created dart storage path definitions in lib.

Fixed issue 32.

### CODE REVIEW

**Review by apolat2000 — CHANGES_REQUESTED** [review]
@CoachBenedetto plural is "paths" not "pathes"

**Comment by apolat2000** [comment]
> @CoachBenedetto plural is "paths" not "pathes"

But if you tested this, particularly some edge cases, LGTM :) I will approve after you fix the typo

**Comment by CoachBenedetto** [comment]
I'll fix the typo. Testing is not possible as it is not bound into the flutter app. This should be done when integrating it into the app. I'll add a todo annotation within the file concerning that.

**Comment by CoachBenedetto** [comment]
Required changes are done @apolat2000

**Review by apolat2000 — APPROVED** [review]
Thank you, LGTM :)

**Pull request merged**
