### PR TITLE
minor api changes added

### PR DESCRIPTION
**Pull request by CoachBenedetto**
Fixed issue 44 and 45.

### CODE REVIEW

**Comment by apolat2000** [comment]
@CoachBenedetto Thanks for the PR! 

It is a good idea to separate the tags of different data. Also, can you make it so that levels and entities can be queried bidirectionally by using `hasMany` and `belongsTo`? It will be quite handy to have and we will need it eventually.

Here is a checklist:
- [ ] Add separate types for the tags of data, e.g. `InterventionTag`, `EntityTag`, `LevelTag`...
- [ ] Bidirectional querying between levels and entites, "_level has many entities, entity belongs to level_".

**Comment by CoachBenedetto** [comment]
I think adding multiple TagTypes adds work and takes value. Using one type of tags makes it possible to query and order different types together considering their context.

Concerning the bidirectional connection. Those are quite unhandy (we'd need to update the level object each time we create/delete an entity). I would propose creating a secondary index for entities so we can query those by level? This would be the leaner way in my opinion 
@apolat2000

**Comment by apolat2000** [comment]
> 

Yeah but no one even knows beforehand that these tags will eventually be used for clustering and filtering data. And also our data types are so different from each other that setting a tag "important" to an intervention won't make sense for an entity (village?) and vice versa. This mixed querying can be done by considering already existing relations between types for a more natural and easier clustering for the user. E.g. searching for the intervention name "farm", the user can see all related levels, entites and surveys etc.

Second point: when `@manyToMany` and `@belongsTo` are used, amplify generates such queries and mutations that the bidirectional relations are read and mutated in single queries and mutations. So it won't lead to inconsistencies.

What do you think? @CoachBenedetto

**Comment by CoachBenedetto** [comment]
I'll add the many to many connection if it possess benefits on the side of the admin app.

Nevertheless, I think adding different tag types is possible later on with ease and so I'd prefer to leave those out for mvp if we do not directly have a use case.

**Comment by CoachBenedetto** [comment]
Ah,

and if a many to many connection would require inappropriate additional work for creating the transfer script by @ChristophNetsch we should not do it?

**Review by apolat2000 — APPROVED** [review]
LGTM

**Pull request merged**
